export default [
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-1-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-1-2.jpg",
    cat: "Snaks",
    title: "Seed of Change Origanic Quinoa,Brown,Rad Rice",
    by: "NestFood",
    price1: "$28.85",
    price2: "$32.0",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-2-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-2-2.jpg",
    cat: "Hodo Foods",
    title: "All Natural Italian-Style Chicken Meatballs",
    by: "Stouffer",
    price1: "$52.85",
    price2: "$55.0",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-3-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-3-2.jpg",
    cat: "Snaks",
    title: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
    by: "StarKist",
    price1: "$48.85 ",
    price2: " $52.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-4-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-4-2.jpg",
    cat: "Vegetable",
    title: "Foster Farms Takeout Crispy Classic Buffalo Wings",
    by: " NestFood",
    price1: "$17.85",
    price2: "$19.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-5-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-5-2.jpg",
    cat: "Pet Foods",
    title: "Blue Diamond Almonds Lightly Salted Vegetables",
    by: "NestFood",
    price1: "$23.85",
    price2: " $25.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-6-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-6-2.jpg",
    cat: "Hodo Foods",
    title: "Chobani Complete Vanilla Greek Yogurt",
    by: "NestFood",
    price1: "$54.85 ",
    price2: "$55.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-7-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-7-2.jpg",
    cat: "Meats",
    title: "Canada Dry Ginger Ale – 2 L Bottle - 200ml - 400g",
    by: "NestFood",
    price1: "$32.85 ",
    price2: "$33.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-8-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-8-2.jpg",
    cat: "Snack",
    title: "Encore Seafoods Stuffed Alaskan Salmon",
    by: " NestFood",
    price1: "$35.85 ",
    price2: "$37.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-9-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-9-2.jpg",
    cat: "Coffes",
    title: "Gorton’s Beer Battered Fish Fillets with soft paper",
    by: " Old El Paso",
    price1: "$23.85 ",
    price2: "$25.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-10-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-10-2.jpg",
    cat: "Cream",
    title: "Haagen-Dazs Caramel Cone Ice Cream Ketchup",
    by: "Tyson",
    price1: "$22.85 ",
    price2: "$24.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-11-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-11-2.jpg",
    cat: "Coffes",
    title: "Gorton’s Beer Battered Fish Fillets with soft paper",
    by: "Old El Paso",
    price1: "$23.85",
    price2: " $25.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-12-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-12-2.jpg",
    cat: "Hodo Foods",
    title: "All Natural Italian-Style Chicken Meatballs",
    by: "Stouffer",
    price1: "$52.85 ",
    price2: "$55.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-13-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-13-2.jpg",
    cat: "Snack",
    title: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
    by: " StarKist",
    price1: "$48.85",
    price2: " $52.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-14-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-14-2.jpg",
    cat: "Vegetables",
    title: "Foster Farms Takeout Crispy Classic Buffalo Wings",
    by: " NestFood",
    price1: "$17.85",
    price2: "$19.8",
  },
  {
    img1: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-15-1.jpg",
    img2: "https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-15-2.jpg",
    cat: "Pet Foods",
    title: "Blue Diamond Almonds Lightly Salted Vegetables",
    by: "NestFood",
    price1: "$23.85 ",
    price2: "$25.8",
  },
];
